config/routes.rb
Rails.application.routes.draw do
  resources :pins
  root 'pins#index'
  devise_for :users
  get 'home/about'
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/pin.rb
class Pin < ActiveRecord::Base
    belongs_to :user
    has_attached_file :image, :styles => {:medium => "300x300>", :thumb => "100x100>" }
    validates :description, presence: { message: "must be entered." }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

    def validation_invalid_type_error_method
        errors.add(:content_type, "You have selected an invalid content type. Please try again.")
    end
end

#validation_presence_error_method
#validation_invalid_type_error_method
#pin.errors[:presence]
#pin.errors[:content_type]

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up)<<:name
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /pins
  # GET /pins.json
  respond_to :html
  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page=> params[:page], :per_page=>3)
  end
  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
    
  def create
    @pin = current_user.pins.build(pin_params)
    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
                end
  end
  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  
    def pin_params
        params.require(:pin).permit(:description,:image, :name)
    end
        
    def correct_user
      @pin = current_user.pins.find_by(params[:id])
      redirect_to pins_path, notice: "Not authorised to edit this pin" if @pin.nil? 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
    
    def submit_text
        @action
    end
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to "Pinterested", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Us", home_about_path %></li>
        <li>
          <% if current_user %>
            <li><%= link_to "Add Pin", new_pin_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to"Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
             <li><%= link_to "Sign In", new_user_session_path %></li>
             <li><%= link_to "Join", new_user_registration_path %></li>
             <li><%= link_to "Show Pins", pins_path %> </li>
          <% end %>
        </li>      
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>About Me...</h1>
<p> My Name Is Joschka Hoffmann and I'm building a pinterest clone</p>

app/views/home/index.html.erb
<div class="jumbotron"> 
    <div class="container">
        <h1> Welcome To My App</h1>
        <p1> It's gonna kick ass. </p1>
        </br>
        </br>
        <%= link_to "About Us", home_about_path, class: "btn btn-default" %>
        <%= link_to "Home", root_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "home/header" %>
<div class="container">
  <% flash.each do |name, msg|%> 
      <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: {multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div class="alert alert-warning" 
      <strong> Oooops. An error has occured.</strong>
        <h5 style= "color:red"; ><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:
        <% @pin.errors.full_messages.each do |message| %>
        <%= message %></h5>
        </br>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-group" %>
  </div>

<div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-group" %>
  </div>
  
  <div class="form-group">
    <%= f.submit submit_text, {class: "btn btn-primary"} %>
  </div>
  </div>
  
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
    <% @pins.each do |pin| %>
        <div class="box">
            <div class="panel panel-default">
                <%= link_to image_tag(pin.image.url(:medium)), pin %> <br/>
                <div class="panel-body">
                    <%= pin.description %>
                    <br/><strong><%=pin.user.name if pin.user %></strong>
                </div>
                <div class="panel-footer"> 
                    <% if pin.user == current_user %>
                        <%= link_to 'Edit', edit_pin_path(pin), class: "btn btn-default" %> <br/>
                        <%= link_to 'Destroy', pin, method: :delete, class: "btn btn-default", data: { confirm: 'Are you sure?' } %><br/>
                    <% end %>
                </div>
            </div>
        </div>    
    <% end %>
    <br/>
    <%= link_to 'New Pin', new_pin_path, class: "btn btn-primary"%>
</div>
<div class="center">
     <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<div class="container">
<h1>New Pin</h1>
</br>
    <%= render 'form' %>

    <div class="form-group">
    </br>
    </br>    
    <%= link_to 'Back', pins_path, class: "btn btn-default" %>
    </div>
</div>

app/views/pins/show.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
      <%= image_tag @pin.image.url (:medium)%>
      </div>
        <div class="panel-body">
        <%= @pin.description %><br/>
        <%= @pin.user.name %> <br/>
          <% if @pin.user == current_user %>
            <%= link_to 'Edit', edit_pin_path(@pin) %> |
            <%= link_to 'Back', pins_path %>
          <%end%>
        </div>
    </div>
  </div>
</div>